apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reto-app-prod

resources:
- namespace.yaml
- ../../base

replicas:
- count: 2
  name: backend
- count: 2
  name: frontend

patches:
- patch: |
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30081
  target:
    kind: Service
    name: frontend

images:
- name: svillegas/reto-backend
  newName: svillegas/reto-backend
  newTag: 1f4c530a4bea458d8a99f099da117a57922dcafe
- name: svillegas/reto-frontend
  newName: svillegas/reto-frontend
  newTag: 1f4c530a4bea458d8a99f099da117a57922dcafe
