apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reto-app-staging

resources:
- namespace.yaml
- ../../base

replicas:
- count: 1
  name: backend
- count: 1
  name: frontend

images:
- name: svillegas/reto-backend
  newName: svillegas/reto-backend
  newTag: 815892f65e939c461d41c05607c1257dcbb740b3
- name: svillegas/reto-frontend
  newName: svillegas/reto-frontend
  newTag: 815892f65e939c461d41c05607c1257dcbb740b3
